// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models;

public partial class Booking
{
    public Guid Id { get; set; }

    public Guid GuestId { get; set; }

    public Guid ListingId { get; set; }

    public DateTime CheckInDate { get; set; }

    public DateTime CheckOutDate { get; set; }

    public int GuestsCount { get; set; }

    public decimal TotalPrice { get; set; }

    public string Status { get; set; }

    public DateTime? BookingDate { get; set; }

    public DateTime? UpdatedAt { get; set; }

    public string SpecialRequests { get; set; }

    public string CancellationReason { get; set; }

    public decimal? SecurityDeposit { get; set; }

    public int? CurrencyId { get; set; }

    public virtual Currency Currency { get; set; }

    public virtual ApplicationUser Guest { get; set; }

    public virtual Listing Listing { get; set; }

    public virtual ICollection<Payment> Payments { get; set; } = new List<Payment>();

    public virtual ICollection<Review> Reviews { get; set; } = new List<Review>();
}